name: postman_collection
description: postman collection schema with freezed and json_serializable
version: 0.0.1

environment:
  sdk: ^3.4.0

dependencies:
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

  build_runner: ^2.4.11
  freezed: ^2.5.6
  json_serializable: ^6.8.0

scripts:
  w: flutter pub run build_runner watch --delete-conflicting-outputs
  g: flutter pub run build_runner build --delete-conflicting-outputs

  publish: flutter pub publish --dry-run
